# Generated by Django 5.1.1 on 2024-09-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_carrest_delete_bookrest'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrest',
            name='color',
            field=models.CharField(default='Black', max_length=40, verbose_name='Car Color'),
        ),
        migrations.AddField(
            model_name='carrest',
            name='horsepower',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='carrest',
            name='manufactured',
            field=models.DecimalField(decimal_places=2, default=1999, max_digits=10),
        ),
        migrations.AddField(
            model_name='carrest',
            name='max_speed',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=15),
        ),
    ]
