# Generated by Django 5.1.1 on 2024-09-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_carrest_color_carrest_horsepower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrest',
            name='horsepower',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='carrest',
            name='manufactured',
            field=models.IntegerField(default=1999),
        ),
        migrations.AlterField(
            model_name='carrest',
            name='max_speed',
            field=models.IntegerField(default=100),
        ),
    ]
